### ISSUE TITLE
Assertions failing to verify

### ISSUE THREAD

**Issue by 0152la** [TrustedCloud/slashconfidential#18]
Some assertions do not verify when ran with Boogie. Breakdown per benchmark:
- UserUsage -- 2
- astar -- 3
- bzip2 -- 7
- CondJmp -- 42
- stackread -- 2

The full list is attached: [errorlog.txt](https://github.com/TrustedCloud/slashconfidential/files/436295/errorlog.txt).

**Comment by rsinha** [comment]
astar:benchmarks\astar\Random\func_00000000000001C0<baseline,5> - should fail because astar wasn’t linked properly i.e. contains store to the constant address 454, which is strange.
astar:benchmarks\astar\Random\func_00000000000001C0<baseline,11>  - should fail because astar wasn’t linked properly i.e. contains store to the constant address 454, which is strange.
astar:benchmarks\astar\Random\func_00000000000001C0<baseline,17>  - should fail because astar wasn’t linked properly i.e. contains store to the constant address 454, which is strange.
bzip:benchmarks\bzip2\bzip2\func_0000000000001750<baseline,11> -  should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
bzip:benchmarks\bzip2\spec\func_0000000000000000<baseline,2> - should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
bzip:benchmarks\bzip2\spec\func_0000000000000000<baseline,8> - should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
bzip:benchmarks\bzip2\spec\func_0000000000000000<baseline,14> - should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
bzip:benchmarks\bzip2\spec\func_0000000000000000<baseline,20> - should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
bzip:benchmarks\bzip2\spec\func_0000000000000070<baseline,24> - should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
bzip:benchmarks\bzip2\spec\func_0000000000000030<baseline,24> - should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
stackread:benchmarks\stackread\func_0000000000001120<baseline,1> - should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
stackread:benchmarks\stackread\func_0000000000001120<baseline,7> - should fail because bzip2 wasn’t linked properly i.e. contains store to some constant address, which is strange.
userusage:benchmarks\UserUsage\func_0000000000001140<baseline,0>\- unconstrained pointer write;  we know about this and report it as a false positive in the PLDI'16 paper
userusage:benchmarks\UserUsage\func_0000000000001140<baseline,9>  — unconstrained pointer write; we know about this and report it as a false positive in the PLDI'16 paper
